- id: doi:10.1016/j.neuron.2022.12.016
  authors:
  - Manuel Beiran\*
  - Nicolas Meirhaeghe\*
  - Hansem Sohn
  - Mehrdad Jazayeri
  - Srdjan Ostojic

- id: doi:10.1016/J.TINS.2020.11.007
  authors:
  - Hansem Sohn\*
  - Nicolas Meirhaeghe\*
  - Rishi Rajalingham
  - Mehrdad Jazayeri

- id: doi:10.1016/J.NEURON.2019.06.012
  authors:
  - Hansem Sohn\*
  - Devika Narain\*
  - Nicolas Meirhaeghe\*
  - Mehrdad Jazayeri
